# Generated by Django 4.2.4 on 2023-09-01 22:21

from django.db import migrations, models
import turnos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(validators=[turnos.models.validar_dia])),
                ('horario', models.CharField(choices=[('1', '17:00'), ('2', '18:00'), ('3', '19:00'), ('4', '20:00')], max_length=20)),
                ('motivo', models.CharField(choices=[('1', 'Asesoramiento integral.'), ('2', 'Gestión de documentos argentinos.'), ('3', 'Gestión de documentos italianos.'), ('4', 'Juicio por falta de turnos.'), ('5', 'Asesoramiento por ciudadanías en Italia.'), ('6', 'Asesoramiento por ciudadanías via consulado italiano.')], max_length=100)),
                ('profesional', models.CharField(choices=[('1', 'Dr. Nicolas Vaca Cianferoni'), ('2', 'Dra. Agustina Afur')], max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('horario', 'fecha')},
            },
        ),
    ]
