# Generated by Django 4.2.4 on 2023-09-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_turno_pagado_alter_turno_horario_alter_turno_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
