# Generated by Django 4.2.4 on 2023-09-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_turno_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='pagado',
            field=models.CharField(default='No', max_length=2),
        ),
    ]
